### PR TITLE
Show Progress Needed This Year On Graphs To Provide More Context

### LINKED ISSUE #169: Show Progress/Trend On State Details Progress Graphs
In our initial batch of user interviews multiple users expressed feeling saddened when they saw our progress graphs, like this one from the [Illinois state details page](https://decarbmystate.com/illinois) under transportation:

Screenshot from 2023-01-03 21-51-12

We should figure out a way to show progress or a sooner term goal for this graph - since we don't know how policies will impact future growth (e.g. tax credits or permitting changes speeding up certain tech deployments) an easy interim solution would be to show a dashed section for the next year goal. In the graph above that would be 153k vehicles compared to the current 26k which is still 5.6 times the green slice but is more manageable than seeing a giant orange bar.

Since we don't have a final concept, I'd try a few styling options and show different ideas in the PR.

### PR DESCRIPTION
**Pull request by SuragNuthulapaty**
## Overview

Updates the progress bars to look less gloomy and give an indicator on how much progress is needed in the next year
Closes #169

### Demo

Screenshot 2023-02-07 at 9 25 17 PM

## Testing Instructions

go to any state page and check each of the progress indicators

### CODE REVIEW

**Comment by vkoves** [comment]
@SuragNuthulapaty - the new section is missing on the power section, can you add it to that?

Screenshot from 2023-02-08 14-10-23

I also think two slight CSS tweaks make this look better:

```
fill: #6c757d;
font-size: 0.75rem;
```

This increases a font a touch to 12px, which is a good minimum text size, but lightens the text.

Screenshot from 2023-02-08 14-12-41

**Comment by derekeder** [comment]
I think this is moving in a good direction, but the addition of a third color makes this bar chart a bit harder to parse. We need to label each section somehow. The note under the bar is not enough. A few ideas:

* use `recharts` to render it as a single bar chart and enable hover/tap functionality to show values and labels. Here's an example of what I'm thinking: https://recharts.org/en-US/examples/SimpleBarChart
* similar to how we show the black reference lines on the [about page](https://decarbmystate.com/about/) for the electrification chart, we could show them below this chart as well

**Comment by vkoves** [comment]
Subtle, but the MWs graph is getting cut off at the top:

Screenshot from 2023-02-14 21-03-00

**Comment by vkoves** [comment]
@SuragNuthulapaty - sorry, I also noticed the colors of the graphs are different 😆 

Screenshot from 2023-02-14 21-18-39


Screenshot from 2023-02-14 21-18-34
Maybe we really should move those into one component, but I'll leave that up to you if you want to take that on.

There's also no right label on that graph but maybe you and @derekeder discussed not needing that for the power graph 🤷🏻‍♂️

**Comment by derekeder** [comment]
I agree we could use some consistency here. It might look better to not have the right label shown at all.

Moving everything into a single component will probably make these changes easier, but up to you @SuragNuthulapaty

**Comment by SuragNuthulapaty** [comment]
Sounds good, I’ll move both charts into one component

**Comment by SuragNuthulapaty** [comment]
@derekeder I combined the graphs, if you want to take a look at this now

**Review by derekeder — APPROVED** [review]
looks great! nice work

**Pull request merged**
