### PR TITLE
Fix graph

### LINKED ISSUE #129: Clarify Missing Emissions Data for 2019-2022 in Area Chart
There's a gap between 2018 and 2022 in our area chart:
Screen Shot 2022-07-19 at 7 56 34 PM

Option 1: find state totals for the missing years and fill them i9n

Option 2: show greyed out estimate section for the missing years

### PR DESCRIPTION
**Pull request by hkier**
## Overview

This PR contains the updates to simpleareachart.js which fixes the problem of the graph failing to indicate there is missing data for several years.  Prior to this fix, the graph just skipped over the years with missing data.

Closes #129 

### Demo
Screenshot 2022-07-30 at 15-39-16 What does it take to decarbonize your state

### Notes
There is no simple way to center the legend which says "Missing Data" as recharts will place the reference point on a specific x value.  

## Testing Instructions

Make your changes and then visually check the graph to assure the result is as you expect.  This needs to be checked for several different states.

### CODE REVIEW

**Comment by vkoves** [comment]
@hkier - there's some merge conflicts, mind taking a look at those? I don't think we merged stuff super recently though so I'm a little puzzled

**Comment by hkier** [comment]
Yes I was quite surprised by the merge conflicts as I thought I had pulled from main.  I also only changed one file so I am puzzled as to why the 2nd file showed up.

**Comment by hkier** [comment]
I have a suspicion as to what may have occurred to create the merge conflicts.  It appears there is both a "main" branch and a "master" branch (created 3 months ago).  I have a feeling I may have created "fix-graph" from the wrong branch.  If we don't need "master" it should be deleted to prevent further problems.

@vkoves

**Comment by hkier** [comment]
@vkoves Now I wonder the best way to solve these conflicts.  Should I just save a copy of the changed file, kill the branch and then redo it?

**Comment by vkoves** [comment]
If you can pull that off that seems reasonable to me @hkier, sometimes you just need a clean start!

**Pull request closed without merging**
