### PR TITLE
Update About Page With Questions Split Into FAQ & Team Photos

### LINKED ISSUE #55: Flesh Out the About Page
We should flesh out the about page explaining generally:

- Who made this
- Why we made it
- Our sources?

### PR DESCRIPTION
**Pull request by vkoves**
## Overview

Updates the about page with a Team section showing photos of three of our team members, and moved questions to the FAQ

Additionally, I updated the homepage text so it says: "**Choose Your State** To Learn How It Can Decarbonize", which seems clearer than "See Details on How Your State Can Describe".

Closes #55

### Demo

| New FAQ Section | New About Section |
| --- | --- |
| Screenshot from 2023-01-15 21-37-14 | Screenshot from 2023-01-15 21-37-31 |

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

-  Test homepage, `/about`, and `/faq` on mobile and desktop

### CODE REVIEW

**Review by derekeder — CHANGES_REQUESTED** [review]
I really like the FAQ changes.

For the headshots, a few things:
- I think we should wait until we have a few more before making this live. Surag, Sean, Dylan, Howard and Robert all made significant contributions and I'd like to feature them. Could we pull those changes out into another PR?
- Viktor is listed twice - once in the photo section and once in the list below

**Comment by vkoves** [comment]
@derekeder - I can fix myself being listed twice, but I don't know when those folks will get me photos, so I'd rather get this up now and add them later. Three team photos looks better than none in my book, and it's already been a week since I posted in Slack asking for headshots.

**Comment by derekeder** [comment]
let me ping a few people directly and see if we can get some more headshots for this PR

**Comment by vkoves** [comment]
@derekeder - updated to remove myself being double listed and reordered contributors, since I noticed Surag and Robert were last despite having made a lot of PRs. I also think we could make it so we have a list of folks, with more space dedicated to each person even if they don't have an image.

**Comment by vkoves** [comment]
@derekeder - the about page is now updated with more folks!

| Desktop | Mobile |
| --- | --- |
| Screenshot from 2023-01-21 18-20-38 | Screenshot from 2023-01-21 18-18-13 |

**Review by derekeder — APPROVED** [review]
nice - looks great!

**Pull request merged**
