### PR TITLE
Add pictures to and reorganize state detail page

### PR DESCRIPTION
**Pull request by jpvelez**
## Overview

This PR:
- adds pictures to be more visually engaging
- changes font size and spacing to more visually engaging
- shortens and simplifies and punches up copy as much as possible
- makes slight changes to how content looks in mobile mode: pollution bar chart now comes before overview sentence, e.g. "30% of NYS's pollutions comes from ..."

### Buildings

Screen Shot 2022-07-10 at 3 11 59 PM

- In this section, we're still using my sister's raster images. @jmadans Can you have Josephine make vector versions in her style? Odds are she is already going to for the video.

Screen Shot 2022-07-10 at 3 12 52 PM

- @jmadans here as well, we'll need J to make some kind of "zooming out and seeing different kinds of buildings pollution and then becoming electrified and then not polluting." (see the car section for example) This is part of the video as well.

### Cars
Screen Shot 2022-07-10 at 3 14 19 PM

- @vkoves these vehicles need to be aligned properly
Screen Shot 2022-07-10 at 3 15 04 PM

- @vkoves they also become kind of huge in one of the narrowed views.. adjust?

Screen Shot 2022-07-10 at 3 15 39 PM

- @vkoves these will need to be positioned better and ideally.. animated? Like each car "pops" from being gray to colorful, one at a time?

### Power

Screen Shot 2022-07-10 at 3 16 38 PM

- @jmadans @vkoves  this picture is nice but I think we need something with smaller dimensions?
- @jmadans also, the vector file is absolutely massive, like 2MB. I can't really shrink it because there's just a lot of detail in it. Can you ask J to make something with fewer internal polygons, so it loads faster?

Screen Shot 2022-07-10 at 3 17 57 PM

- @jmadans Can you ask J to provide one with a panel on a roof? Pretty sure she's doing this for the video.

Screen Shot 2022-07-10 at 3 18 37 PM

- @jmadans Can you ask J to provide pictures of a small gas plant and small wind and solar farms? So far she only has files for a single panel and single turbine, which you can see in the images folder. Again, she'll probably be producing these for the video anyway.

Screen Shot 2022-07-10 at 3 19 39 PM
- @vkoves I cut down the number of plants so they would fit on a single row.. it was too cluttered and broke the flow of the story. @jmadans we'll need J to draw little coal and oil plants in addition to the little nat gas plant. Which makes me think... maybe she can draw 4 variations of each type of plant? That way they each look distinct in the row, instead of repetitive. Again, she might have to make multiple variations of gas plants for the video anyway.

Screen Shot 2022-07-10 at 3 21 54 PM

- @jmadans We'll need a couple of picture here to break up the text and tell the story visually. Something that shows why/how we need 2x more power than we have now (maybe the power strip metaphor J is doing for the video?) And also something that shows lots of wind and solar farms being built--just like the sections above that show a lot of buildings being electrified and cars being converted.

## Bugs

- I commented out the area chart because it's not finding the data and so won't render the page.
- I also somehow broke the color highlighting of the right-hand-side each section for every section except for Buildings. Not sure how, sorry!

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

### CODE REVIEW

**Comment by vkoves** [comment]
@jpvelez - I can dig into this a bit, but it looks like most of these are giant PNGs, not SVGs:

Screenshot from 2022-07-10 21-15-54

If that's what you have, that's okay - I can easily crop these down to size and optimize them, but an SVG would be ideal.

**Comment by vkoves** [comment]
Also I'm curious for @derekeder's thoughts on this, but I find emojis in the middle of sentences really distracting and just make it harder to read.

**Comment by derekeder** [comment]
I agree having both the emoji and the hand drawn graphics is too distracting. Lets let the hand drawn graphics do most of the work and keep the text simple.

**Comment by jmadans** [comment]
@vkoves @derekeder Are the SVGS still too big? Meeting with illustrator at 6pm CDT so let me know asap

**Comment by derekeder** [comment]
@jmadans if they're png files, we can resize them to be smaller.

**Comment by vkoves** [comment]
I think the svgs should be fine - if not I'm comfortable doing some cleanup myself!

**Comment by vkoves** [comment]
Juan for when you get back - please for the love of god let's get you added to the GitHub repo, dealing with a fork just for this branch is a real headache 😅

**Comment by vkoves** [comment]
Closed in favor of #130, which I created by copying over the fork branch. What a mess

**Pull request closed without merging**
