### PR TITLE
Make State Title and Back Button Sticky

### LINKED ISSUE #46: Make State Details Page Graph Sticky
Make the graph order match the section order and make the graph sticky, using a scroll observer to update the graph based on where you are on the page.

### LINKED ISSUE #66: State Header should be included with sticky single bar
The header information at the top of the page should be included with the sticky single bar bar graph as the user scrolls down the page.  Most importantly, the user should be able navigate back to the map or other pages without having to scroll all the way back to the top of the state details page.

### PR DESCRIPTION
**Pull request by vkoves**
## Overview

Makes the state name and back button on the state details page sticky so that you can easily see what state you are on and go back to the map at any point.

| Desktop | Mobile |
| --- | --- |
| Peek 2022-05-03 22-15 | Peek 2022-05-03 22-16 |

Closes #66  

### Demo

See Overview.

### Notes

None.

## Testing Instructions

- Test on desktop confirming you can scroll and see the state title (include with long titles like District of Columbia)

### CODE REVIEW

**Review by derekeder — COMMENTED** [review]
a few thoughts:

* as we scroll, it would be great to see 'What does it take to decarbonize my state` above the state icon and title
* is it possible to have the sticky header take the full width of the page? on mobile especially it looks a little weird:
Screen Shot 2022-05-03 at 10 32 31 PM

**Comment by vkoves** [comment]
@derekeder - both of those are now fixed, let me know what you think. Here's a demo:

Peek 2022-05-03 22-47

**Review by derekeder — DISMISSED** [review]
nice - love it. 

my last thought is it would be nice to reduce the height of the state title section now that its always showing on the page. with the navbar it takes up a good portion of the viewing area

**Comment by hkier** [comment]
Can we do something like this
Screenshot 2022-05-04 at 09-51-16 What does it take to decarbonize your state
:

**Comment by vkoves** [comment]
@derekeder - I've now cut the padding a bit to reduce that size on desktop and mobile, let me know what you think

**Review by derekeder — APPROVED** [review]
looks good! we can bring this in

**Pull request merged**
