### PR TITLE
Generate All 3.5K Power Plant Social Images

### LINKED ISSUE #200: Create Custom Meta Images for Power Plant Pages
We should create custom meta images for power plant pages, like we did for the state pages for issue #97 in PR #137. Here's what it looks like now if you share a power plant page:

image

Even something replicating the top of the page would be a good start, but if we integrate Google Maps imagery using that would be even better.

### PR DESCRIPTION
**Pull request by vkoves**
## Overview

Adds new social card images for **all** power plants, which look like this:

image

This process involved a few steps:

1. **Creating a new power plant social card route that renders the card** - this was based off of the SocialCardPage and takes a `state` and `plant` param, like `/power-plant-social-card/?state=new_york&plant=ravenswood-generating-station`
2. **Update the generate-social-cards script to also generate power plants** - this actually was the hardest part of the work, since power plants number about 3.5 thousand, so I added enhancements to the script like command line arguments that let you opt into a debugging mode with more logging and browser previews (`--debugging`), and a headless flag (`--headless) that you can combo with debugging. Also updated the `README` and `package.json` with new helpers and explanations
3. **Ran the script against Netlify** - I made this draft PR, got a Netlify preview, updated the `SiteDomain` in `generate-social-cards.js` to that domain, and then ran `yarn generate-social-power-plants`. This was needed because `gatsby develop` always eventually bombs out due to memory issues  😖 
4. **Copy the output directory into static**

And that's it! 🎉 

Closes #200

### Demo

| Console Command Output with `--debugging` flag | Social Card URL |
| --- | --- |
| Screenshot from 2023-05-03 08-32-54 Screenshot from 2023-05-03 08-23-24 | Screenshot from 2023-05-03 08-33-59 Screenshot from 2023-05-03 08-35-05 |

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

1. Test the actual social generation scripts and making sure you can run them and understand them - if not, I need to tweak the documentation
2. Confirm a power plant page has a `<meta name="image"` tag with a `content` pointing to a valid exported social card image (but using the prod `decarbmystate.com` domain rather than `localhost`).

### CODE REVIEW

**Comment by vkoves** [comment]
A few notes as I've been working on this - this is a headache because:

1. We have 3.4 thousand power plant pages (and this is not limited to just coal, oil, and gas, which is probably fine)
2. `gatsby develop` watches the `static` directory and seems to error out after too many rebuilds
3. `gatsby develop` also seems to eat up more RAM with each request, and will eventually run out of memory after ~250 social card requests. This is likely because each page is pulling all power plants with GraphQL

My big solution has been improved logging and a way to restart at a given index, but I am also trying out hitting this PR's deploy preview to see if that helps - that way I just have a long running command making network requests over and over, rather than something hosting and another script hitting it.

**Comment by vkoves** [comment]
**Update:** My last commit fixes that, the trick was to use `useEffect` so that Gatsby runs the URL query param checks at runtime, rather than build time.

Screenshot from 2023-05-03 01-58-45

**Comment by vkoves** [comment]
I let it run overnight against Netlify, and with a 1,000 image head start it took 4,456 seconds, or 74 minutes.

Screenshot from 2023-05-03 08-23-24

That means (roughly) the full set would take about two hours.

**Review by derekeder — APPROVED** [review]
this one is a beast! code makes sense and I tested a few power plant images and they work.

i'm good with merging this in.

**Pull request merged**
