### PR TITLE
Accessibility Fixes 2 - Fix Homepage Map Keyboard Use & Add Skip to Main Link 

### LINKED ISSUE #91: Accessibility: Missing Header Skip to Main Content Link
Learn more from [this page from University of Illinois](https://fae.disability.illinois.edu/rulesets/BYPASS_1/), but basically we need a skip link so keyboard users don't have to tab through the header after every single navigation.

### PR DESCRIPTION
**Pull request by vkoves**
## Overview

Fixes some last accessibility issues, in particular:

1. Not being able to use the map on the homepage to navigate with just the keyboard (it was tabbable, but hitting Enter didn't navigate)
2. Not having a skip to main content link - you can now hit tab from the URL bar, hit Enter on the skip link, then hit tab to be on the first interactive element in the main content
3. Fixed a minor hold-over `aria-labelledby` attribute.

See the demo section for a better demo of the skip link.

This PR closes #91 and #90

### Demo

| Homepage Skip Demo | State Details Skip Demo |
| --- | --- |
| Peek 2022-05-17 20-38 | Peek 2022-05-17 20-39 |

### Notes

None.

## Testing Instructions

* Test the skip link on **all pages** and confirm that if you hit tab you go to the next interactive element (sometimes the footer link if the page is empty)
* Test that you can use the homepage state map using just the keyboard - press Tab to get to the state you want, then press Enter to navigate to that state

### CODE REVIEW

**Comment by vkoves** [comment]
@derekeder - can you record a video of what you're seeing? What specific elements are impacted? An ordinary `<a>` tag with an `href` should be tabbable and what not by default and I could activate links like the heat pump link or our example.com call to action links.

**Comment by derekeder** [comment]
@vkoves sure thing. i used to use liceCAP for recording gifs but its no longer supported on my OS. what's your go-to?

**Comment by vkoves** [comment]
@derekeder - I typically use Peek gif recorder on Linux, but that won't help you much. This [Apple support article](https://support.apple.com/en-us/HT208721) suggest it's built into Mac OS. GitHub then lets you upload MP4 files and there's lots of sites to convert any video format into MP4 if needed.

**Comment by derekeder** [comment]
@vkoves how about that - did not know about the video feature. I use screenshots all the time, but this is new to me!

Here's a video of me tabbing through the pages. Home page works fine, but when i get to a state detail page, I can only tab through the FireFox UI elements (arrows, reload, url bar, etc)

https://user-images.githubusercontent.com/919583/169569624-2dc53a43-9a1a-4039-925a-9cd2635c4b56.mov

**Comment by vkoves** [comment]
@derekeder - this is an issue with Mac where you have to flip a setting to tab links, check this out: https://css-tricks.com/proper-tabbing-to-interactive-elements-in-firefox-on-macos/

**Comment by derekeder** [comment]
how about that - did the trick. learning lots about accessibility on this project!

**Review by derekeder — APPROVED** [review]

**Pull request merged**
