### PR TITLE
Move to New Illustrations for State Details Page & Tweak Wording

### PR DESCRIPTION
**Pull request by vkoves**
## Overview

**Note:** This PR is a clone of PR #121 but moved to this repo. See that PR for initial discussion.

This PR:
- adds pictures to be more visually engaging
- changes font size and spacing to more visually engaging
- shortens and simplifies and punches up copy as much as possible
- makes slight changes to how content looks in mobile mode: pollution bar chart now comes before overview sentence, e.g. "30% of NYS's pollutions comes from ..."

**Note:** Juan-Pablo had mentioned doing some animations with these illustrations, but this PR already took me a ton of work (mainly doing SVG cleanup, cleaning up the code, etc.) and has been open for several weeks, so I wanted to start with a non-animated clean state that we can then improve on. I already thing this is a huge upgrade!

**♿ Accessibility Note:** I did not specify alt-text for these new illustrations, since they are _purely decorative_ (you can delete them and the site still makes sense, it just doesn't look as pretty).

## Screenshots

Here's some screenshots of the notable sections with the new illustrations

| Buildings Top | Buildings Bottom | Transport Top | Transport Bottom |
| --- | --- | --- | --- |
| Screenshot from 2022-08-07 15-28-30 | Screenshot from 2022-08-07 15-28-47 | Screenshot from 2022-08-07 15-28-56 | Screenshot from 2022-08-07 15-29-05 |

## Testing Instructions

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected output

### CODE REVIEW

**Comment by vkoves** [comment]
@jmadans - I noticed around the plug the illustrations have a white background, could you fix that with the illustrator?

image

And I noticed that the SVGs are indeed ginormous, but I should be able to handle that on my end with compression - I'd rather we store the raw original illustration and then downscale them as needed.

**Comment by vkoves** [comment]
@jmadans - did the illustrator provide assets for a dirty building, dirty stove and heater, and an induction stove? Also the solar panel seems a bit bare - I think having it on a stand would make more sense for our context if that's possible. If not, I can try to make it work.

| Buildings | Solar Panel |
| --- | --- |
| Screenshot from 2022-07-24 18-22-04 | Screenshot from 2022-07-24 18-22-11 |

**Comment by jmadans** [comment]
Okay here's an update based on a punch list I derived on the previous comments from @vkoves and Juan. 

1. Vector images for Heat pump, induction stove, water heater, and gas stove, bad builidng. 
**Status:** Still waiting to get access to these. 
3. Building. CAn we make something with fewer internal polygons for. Digitally - we could make a silhouette.  Trace it and make it black. Bring vector into illustraor, select all and just make it a shape.  Cover it in black so that it just a silhoutte. 
**Status:** Simpler version sent to @vkoves 
5. Buildings become non-polluting. Polluting buildings, electrifying buildings, and then clean buildings
Status: Josephine was confident we could make this out of what she's already created. We'll know when I can share access to the dropbox folder
7. Solar panl turn into house with solar panels on it. We'll be able to see it with a building.  Josephine to add solar panel on roof
Status: Better solar panel and small house with solar panel sent to @vkoves 
9. Small gas, wind, and solar. 
Status: Given that Josphine's already has a lot more to do for the video and a liimited time, I'm making the call that we're going to keep the SimCity graphics. 
11. Little coal, and gas plants. Josephine has a coal plant. 
12. Power Strip Metaphor. Carbon power strip and then a power strip with the color coded power sources. Clip off the end of the power strip with animation and double them. This would be something to ask Josephine for. 
Status: Josephine said that the videographer is actually doing the magic to make the power strip animation work for the video. She's confident we can animate the existing power strip similarly on our own/ she said no.

**Comment by jmadans** [comment]
Small copy change I talked about with @vkoves on slack....
Can we change this prompt from "See a map of dirty plants in the US" to "Find the dirty plants near you"

**Comment by vkoves** [comment]
I have updated the text as Jack requested, fixed merge conflicts, and also fixed the bottom section being reverted in this PR to our old "That's it 🎉 " section - it now maintains the take action page end.

**Comment by vkoves** [comment]
One thing I am considering changing (but can defer for later) - the `<hr>` elements now look really clunky on desktop and break the centering. On mobile it's still useful, but I think it would look better without them on desktop:

| Before | After |
| --- | --- |
| Screenshot from 2022-08-13 08-50-46 |  Screenshot from 2022-08-13 08-51-58 |

**Comment by SuragNuthulapaty** [comment]
This looks good for me

**Comment by vkoves** [comment]
Derek hasn't had a chance to review this in over a week, so I'm going to merge this and ask for forgiveness 😆

**Comment by derekeder** [comment]
@vkoves retroactive approval!

**Pull request merged**
