### PR TITLE
State power plants

### LINKED ISSUE #52: render power plants on state detail page
Once #51 comes in, we will have access to 3 lists of power plants: coal, gas and oil.

Following the wireframes, we'll want to iterate over this list and show a power plant icon for each one:

coal
sim-city-coal-plant

gas
sim-city-gas-plant

oil
sim-city-oil-plant

Each one should also show the power plant name, county, utility and MW capacity. This could be done either by hovering or displaying the text below it. The ultimate effect we want is something like what we have in the wireframes:

Screen Shot 2022-04-13 at 9 01 33 PM

### PR DESCRIPTION
**Pull request by hkier**
## Overview
This PR will add the power plants to the states' detail pages.  An icon will be shown for the first 20 power plants.  Anything more than that will be aggregated. 

Closes #052

### Demo

Optional. Screenshots, `curl` examples, etc.

A file has been attached to the PR to demonstrate how the page should appear.

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

This PR can be tested by checking various states' detail pages to verify the power plants are displaying correctly.

* How to test this PR
* Prefer bulleted description
* Start after checking out this branch
* Include any setup required, such as bundling scripts, restarting services, etc.
* Include test case, and expected outpu
[What does it take to decarbonize your state 2.pdf](https://github.com/chihacknight/decarbonize-my-state/files/8535536/What.does.it.take.to.decarbonize.your.state.2.pdf)
t

### CODE REVIEW

**Comment by vkoves** [comment]
@hkier - two immediate things looking at this:

1. There's some hefty merge conflicts, did something go wrong in the git history? If needed we could cherry pick some commits, as I suspect 7ee3f1c is the problem
2. Could we add a quick pluralize so we don't say "X plant**s**" if there's only one? Here's an example:

image

**Comment by hkier** [comment]
@vkoves I am too saw all those "changes" but couldn't figure out what caused it as I only modified 1 file and added the 3 image files (which linux is adding corresponding .identity files).

Along with the improper grammar when there is only 1 plant, I was also thinking about what we should do if there are 1-5 more plants to display.  Do we really want to say +1 more?

**Comment by hkier** [comment]
I think I have a simple fix for all the conflicts.  

1. Save the 4 impacted files in a safe spot.
2. Delete the branch
3. Create a new branch from main
4. Import the 4 files into the new directory
5. pull request

Will this work?  Concerns.

**Comment by hkier** [comment]
I realized I can create a new branch without deleting the problem branch.  I did so, and all seems to work fine.  Therefore, I created PR64 to replace this one so we will not have to work around all the file changes shown from the one commit.  If PR 64 meets approval or will get us to where we want to go, then this PR can be closed/deleted.

**Comment by vkoves** [comment]
Closed, Howard is working on a new PR without the conflicts

**Pull request closed without merging**
