### PR TITLE
Add Satellite Imagery of All Fossil Power Plants

### PR DESCRIPTION
**Pull request by vkoves**
## Overview

Adds satellite images to all power plants do you can see how large a plant is and understand it's environment.

Closes #xxx

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

- How to test this PR
- Prefer bulleted description
- Start after checking out this branch
- Include any setup required, such as bundling scripts, restarting services, etc.
- Include test case, and expected output

### CODE REVIEW

**Comment by vkoves** [comment]
Demo with my API key:

Screenshot from 2023-05-02 21-18-42

**Comment by vkoves** [comment]
@derekeder - we discussed you making a python script so we can now have power plant pages at say `/power-plant-maps/{state-slug}-{plant-slug}.png` or something like that. We don't know that plant names are unique so I think keeping the plant slug in there would be helpful.

**Comment by derekeder** [comment]
@JoseMRodriguezO looks like we're missing your script and the images. Looks like you reverted a commit that had the script in this commit 9c1166456200da22ade27441e35cab1906eb57cd. Can you add it back, as well as the 3,500 images?

**Comment by JoseMRodriguezO** [comment]
will do.

**Comment by JoseMRodriguezO** [comment]
## Overview

This pull request adds functionality to fetch power plant data from a JSON file and save map images for each power plant using the Google Static Maps API.

Closes #XXX

### Demo

image


### Notes

 Added code to read power plant data from a JSON file.
- Iterated through the power plants in each state and saved map images for each power plant.
- Handled directory creation for saving image files.
- Updated the code to use the `json.load()` function to directly load the JSON file.
- Added error handling for potential exceptions during file operations and API requests.
- Refactored the code into separate functions for better organization and reusability.

## Testing Instructions

 Ensure the necessary dependencies, such as `requests` and `slugify`, are installed.
- Checkout this branch and run the code.
- Verify that map images are saved for each power plant in the specified directory.
- Perform thorough testing, including different scenarios and error conditions, to ensure the code functions as expected.

**Comment by vkoves** [comment]
Want to note that this is on my radar and I know I need to get back to this 😆

**Comment by vkoves** [comment]
@derekeder and @JoseMRodriguezO - I've integrated the power plant imagery onto the power plant details page, but there's a few things I noticed. First, here's what I have right now:

Screenshot from 2023-06-18 14-30-39

So what I noticed:

1. We have images for power plants we don't show - maybe we pulled in all power plants and not just gas, coal, and oil? You can technically access these pages though, like ABC Coke in Alabama which must have a data entry issue:

Screenshot from 2023-06-18 14-32-32


2. The images are huge, totallying 1.5 GB. We should move to a modern format like `.webp` or even just a more compressed `.jpg`, because this amount of files will make the repo harder to use but also risks eating up our bandwidth.

**Comment by JoseMRodriguezO** [comment]
ok, I will work on it

**Comment by vkoves** [comment]
@JoseMRodriguezO - we can talk about it on Tuesday, I think we need to use a tool like ImageMagick to locally compress all the images, but not sure about reducing which power plants we have. If you do want to take a crack at it, this is what I found:

https://unix.stackexchange.com/questions/516435/imagemagick-convert-compress-all-files-in-the-directory

My internal target is < 200 KB per image, but if we could get 100 KB that'd be great. https://squoosh.app/ seems to be able to do that without it looking terrible

**Comment by JoseMRodriguezO** [comment]
Hi, Viktor I just finished with imageMagic. I just resize the images to low 200kb at 600x600 I just need to commit now, also separated the plants by category as requested. 
 I just didnt update my commit before pushing. please verify and let me know. 
Thank you,

**Comment by vkoves** [comment]
@JoseMRodriguezO - can you post a before after image with one of your images before and after compression? What does the total directory size come out to?

**Comment by vkoves** [comment]
@JoseMRodriguezO - that sounds awesome! Can you push up the new images?

**Comment by vkoves** [comment]
Sorry I've dropped the ball on this, I need to get the styling fixed up and then get someone to review this! It's on my list 😆

**Comment by vkoves** [comment]
@derekeder - this is still waiting on you, it's ready for review

**Pull request merged**
