### PR TITLE
adding 3 files 1 modified

### LINKED ISSUE #52: render power plants on state detail page
Once #51 comes in, we will have access to 3 lists of power plants: coal, gas and oil.

Following the wireframes, we'll want to iterate over this list and show a power plant icon for each one:

coal
sim-city-coal-plant

gas
sim-city-gas-plant

oil
sim-city-oil-plant

Each one should also show the power plant name, county, utility and MW capacity. This could be done either by hovering or displaying the text below it. The ultimate effect we want is something like what we have in the wireframes:

Screen Shot 2022-04-13 at 9 01 33 PM

### PR DESCRIPTION
**Pull request by hkier**
## Overview

**This replaces PR 63**

This PR will add the power plants to the states' detail pages. An icon will be shown for the first 20 power plants. Anything more than that will be aggregated.

Closes #52

### Demo

Optional. Screenshots, `curl` examples, etc.

### Notes

Optional. Ancillary topics, caveats, alternative strategies that didn't work out, anything else.

## Testing Instructions

This PR can be tested by checking various states' detail pages to verify the power plants are displaying correctly.
[What.does.it.take.to.decarbonize.your.state.2.pdf](https://github.com/chihacknight/decarbonize-my-state/files/8543253/What.does.it.take.to.decarbonize.your.state.2.pdf)

### CODE REVIEW

**Comment by hkier** [comment]
This PR and branch were created by:

1. Creating a new branch from main
2. copying the 3 new and 1 modified file from the other branch
3. testing on my machine
4. committing changes
5. creating this PR

**Comment by hkier** [comment]
Per Victor's request, I have changed the grammar for the text when there is only one plant.  I also moved the plant display logic into a separate component because the code was getting a bit long and messy.  This will provide for better maintainability in the future.

**Comment by vkoves** [comment]
@hkier - it might be easier to sort this out tomorrow, but there's merge conflicts again (😢) but also it looks like your work undoes some stuff, as on your Netlify the state page graph isn't sticky and the heading text is different. I might be able to fix it using your old PR and some git commands though, so we can try that tomorrow.

**Comment by hkier** [comment]
@vkoves The code changes for this PR are well delineated.   So it should not be difficult to merge it into the main branch.  I really tried to keep it simple but I think there was a merge or two which occurred after I created this branch.  I don't think it will take us more than 15 minutes to complete the merge once we get together.

**Comment by vkoves** [comment]
Closed, Howard is working on a new PR without the conflicts

**Pull request closed without merging**
